// Auto-generated mapping file
export const digimonIcons = {
  1: require('../assets/images/digimon/001_Kuramon.png'),
  2: require('../assets/images/digimon/002_Choromon.png'),
  3: require('../assets/images/digimon/003_Dodomon.png'),
  4: require('../assets/images/digimon/004_Pabumon.png'),
  5: require('../assets/images/digimon/005_Punimon.png'),
  6: require('../assets/images/digimon/006_Botamon.png'),
  7: require('../assets/images/digimon/007_Poyomon.png'),
  8: require('../assets/images/digimon/008_Kapurimon.png'),
  9: require('../assets/images/digimon/009_Koromon.png'),
  10: require('../assets/images/digimon/010_Tanemon.png'),
  11: require('../assets/images/digimon/011_Tsunomon.png'),
  12: require('../assets/images/digimon/012_Tsumemon.png'),
  13: require('../assets/images/digimon/013_Tokomon.png'),
  14: require('../assets/images/digimon/014_Dorimon.png'),
  15: require('../assets/images/digimon/015_Nyaromon.png'),
  16: require('../assets/images/digimon/016_Pagumon.png'),
  17: require('../assets/images/digimon/017_Yokomon.png'),
  18: require('../assets/images/digimon/018_Bukamon.png'),
  19: require('../assets/images/digimon/019_Motimon.png'),
  20: require('../assets/images/digimon/020_Wanyamon.png'),
  21: require('../assets/images/digimon/021_Agumon.png'),
  22: require('../assets/images/digimon/022_Kudamon.png'),
  23: require('../assets/images/digimon/023_Gomamon.png'),
  24: require('../assets/images/digimon/024_Coronamon.png'),
  25: require('../assets/images/digimon/025_Zubamon.png'),
  26: require('../assets/images/digimon/026_Solarmon.png'),
  27: require('../assets/images/digimon/027_Terriermon.png'),
  28: require('../assets/images/digimon/028_Tentomon.png'),
  29: require('../assets/images/digimon/029_ToyAgumon.png'),
  30: require('../assets/images/digimon/030_Tapirmon.png'),
  31: require('../assets/images/digimon/031_Hyokomon.png'),
  32: require('../assets/images/digimon/032_Biyomon.png'),
  33: require('../assets/images/digimon/033_Falcomon.png'),
  34: require('../assets/images/digimon/034_Salamon.png'),
  35: require('../assets/images/digimon/035_Bearmon.png'),
  36: require('../assets/images/digimon/036_Penmon.png'),
  37: require('../assets/images/digimon/037_Monodramon.png'),
  38: require('../assets/images/digimon/038_Ryudamon.png'),
  39: require('../assets/images/digimon/039_Lucemon.png'),
  40: require('../assets/images/digimon/040_Elecmon.png'),
  41: require('../assets/images/digimon/041_Gaomon.png'),
  42: require('../assets/images/digimon/042_Crabmon.png'),
  43: require('../assets/images/digimon/043_Gabumon.png'),
  44: require('../assets/images/digimon/044_Kamemon.png'),
  45: require('../assets/images/digimon/045_Kokuwamon.png'),
  46: require('../assets/images/digimon/046_Gotsumon.png'),
  47: require('../assets/images/digimon/047_Kotemon.png'),
  48: require('../assets/images/digimon/048_Shoutmon.png'),
  49: require('../assets/images/digimon/049_Dracomon.png'),
  50: require('../assets/images/digimon/050_Dorumon.png'),
  51: require('../assets/images/digimon/051_Patamon.png'),
  52: require('../assets/images/digimon/052_Huckmon.png'),
  53: require('../assets/images/digimon/053_Palmon.png'),
  54: require('../assets/images/digimon/054_Floramon.png'),
  55: require('../assets/images/digimon/055_Muchomon.png'),
  56: require('../assets/images/digimon/056_Lalamon.png'),
  57: require('../assets/images/digimon/057_Lunamon.png'),
  58: require('../assets/images/digimon/058_Renamon.png'),
  59: require('../assets/images/digimon/059_Lopmon.png'),
  60: require('../assets/images/digimon/060_Impmon.png'),
  61: require('../assets/images/digimon/061_Otamamon.png'),
  62: require('../assets/images/digimon/062_Gazimon.png'),
  63: require('../assets/images/digimon/063_Gizamon.png'),
  64: require('../assets/images/digimon/064_Guilmon.png'),
  65: require('../assets/images/digimon/065_Goblimon.png'),
  66: require('../assets/images/digimon/066_Shamamon.png'),
  67: require('../assets/images/digimon/067_Syakomon.png'),
  68: require('../assets/images/digimon/068_SnowGoblimon.png'),
  69: require('../assets/images/digimon/069_Chuumon.png'),
  70: require('../assets/images/digimon/070_Dracmon.png'),
  71: require('../assets/images/digimon/071_Hagurumon.png'),
  72: require('../assets/images/digimon/072_DemiDevimon.png'),
  73: require('../assets/images/digimon/073_FunBeemon.png'),
  74: require('../assets/images/digimon/074_Betamon.png'),
  75: require('../assets/images/digimon/075_Mushroomon.png'),
  76: require('../assets/images/digimon/076_Armadillomon.png'),
  77: require('../assets/images/digimon/077_Veemon.png'),
  78: require('../assets/images/digimon/078_Hawkmon.png'),
  79: require('../assets/images/digimon/079_Wormmon.png'),
  80: require('../assets/images/digimon/080_Keramon.png'),
  81: require('../assets/images/digimon/081_Aegiomon.png'),
  82: require('../assets/images/digimon/082_Ikkakumon.png'),
  83: require('../assets/images/digimon/083_Airdramon.png'),
  84: require('../assets/images/digimon/084_Angemon.png'),
  85: require('../assets/images/digimon/085_Kabuterimon.png'),
  86: require('../assets/images/digimon/086_Gargomon.png'),
  87: require('../assets/images/digimon/087_Garurumon.png'),
  88: require('../assets/images/digimon/088_Ginryumon.png'),
  89: require('../assets/images/digimon/089_Grizzlymon.png'),
  90: require('../assets/images/digimon/090_Greymon.png'),
  91: require('../assets/images/digimon/091_Coredramon (Blue).png'),
  92: require('../assets/images/digimon/092_GeoGreymon.png'),
  93: require('../assets/images/digimon/093_Strikedramon.png'),
  94: require('../assets/images/digimon/094_Snimon.png'),
  95: require('../assets/images/digimon/095_ZubaEagermon.png'),
  96: require('../assets/images/digimon/096_Sorcermon.png'),
  97: require('../assets/images/digimon/097_Gatomon.png'),
  98: require('../assets/images/digimon/098_Dobermon.png'),
  99: require('../assets/images/digimon/099_Birdramon.png'),
  100: require('../assets/images/digimon/100_Firamon.png'),
  101: require('../assets/images/digimon/101_Veedramon.png'),
  102: require('../assets/images/digimon/102_Buraimon.png'),
  103: require('../assets/images/digimon/103_Peckmon.png'),
  104: require('../assets/images/digimon/104_Mojyamon.png'),
  105: require('../assets/images/digimon/105_Frigimon.png'),
  106: require('../assets/images/digimon/106_Unimon.png'),
  107: require('../assets/images/digimon/107_Raptordramon.png'),
  108: require('../assets/images/digimon/108_Deputymon.png'),
  109: require('../assets/images/digimon/109_Leomon.png'),
  110: require('../assets/images/digimon/110_Reppamon.png'),
  111: require('../assets/images/digimon/111_Icemon.png'),
  112: require('../assets/images/digimon/112_Wizardmon.png'),
  113: require('../assets/images/digimon/113_Witchmon.png'),
  114: require('../assets/images/digimon/114_Gaogamon.png'),
  115: require('../assets/images/digimon/115_Gawappamon.png'),
  116: require('../assets/images/digimon/116_Kiwimon.png'),
  117: require('../assets/images/digimon/117_Kyubimon.png'),
  118: require('../assets/images/digimon/118_Clockmon.png'),
  119: require('../assets/images/digimon/119_Centarumon.png'),
  120: require('../assets/images/digimon/120_Sunflowmon.png'),
  121: require('../assets/images/digimon/121_Seadramon.png'),
  122: require('../assets/images/digimon/122_Coelamon.png'),
  123: require('../assets/images/digimon/123_Shellmon.png'),
  124: require('../assets/images/digimon/124_Starmon.png'),
  125: require('../assets/images/digimon/125_Tankmon.png'),
  126: require('../assets/images/digimon/126_MudFrigimon.png'),
  127: require('../assets/images/digimon/127_Dinohyumon.png'),
  128: require('../assets/images/digimon/128_Tyrannomon.png'),
  129: require('../assets/images/digimon/129_Turuiemon.png'),
  130: require('../assets/images/digimon/130_Togemon.png'),
  131: require('../assets/images/digimon/131_Drimogemon.png'),
  132: require('../assets/images/digimon/132_Dorugamon.png'),
  133: require('../assets/images/digimon/133_BaoHuckmon.png'),
  134: require('../assets/images/digimon/134_Blimpmon.png'),
  135: require('../assets/images/digimon/135_Meramon.png'),
  136: require('../assets/images/digimon/136_Monochromon.png'),
  137: require('../assets/images/digimon/137_Lekismon.png'),
  138: require('../assets/images/digimon/138_IceDevimon.png'),
  139: require('../assets/images/digimon/139_Wendigomon.png'),
  140: require('../assets/images/digimon/140_Woodmon.png'),
  141: require('../assets/images/digimon/141_Ogremon.png'),
  142: require('../assets/images/digimon/142_Octomon.png'),
  143: require('../assets/images/digimon/143_Guardromon.png'),
  144: require('../assets/images/digimon/144_ShellNumemon.png'),
  145: require('../assets/images/digimon/145_Growlmon.png'),
  146: require('../assets/images/digimon/146_Kuwagamon.png'),
  147: require('../assets/images/digimon/147_Gekomon.png'),
  148: require('../assets/images/digimon/148_Geremon.png'),
  149: require('../assets/images/digimon/149_Coredramon (Green).png'),
  150: require('../assets/images/digimon/150_GoldNumemon.png'),
  151: require('../assets/images/digimon/151_Golemon.png'),
  152: require('../assets/images/digimon/152_Cyclonemon.png'),
  153: require('../assets/images/digimon/153_Sangloupmon.png'),
  154: require('../assets/images/digimon/154_Sukamon.png'),
  155: require('../assets/images/digimon/155_Tuskmon.png'),
  156: require('../assets/images/digimon/156_Devimon.png'),
  157: require('../assets/images/digimon/157_Deltamon.png'),
  158: require('../assets/images/digimon/158_Dokugumon.png'),
  159: require('../assets/images/digimon/159_Nanimon.png'),
  160: require('../assets/images/digimon/160_Numemon.png'),
  161: require('../assets/images/digimon/161_Bakemon.png'),
  162: require('../assets/images/digimon/162_Hyogamon.png'),
  163: require('../assets/images/digimon/163_Fugamon.png'),
  164: require('../assets/images/digimon/164_Flymon.png'),
  165: require('../assets/images/digimon/165_PlatinumSukamon.png'),
  166: require('../assets/images/digimon/166_BlackGatomon.png'),
  167: require('../assets/images/digimon/167_Vegiemon.png'),
  168: require('../assets/images/digimon/168_Minotarumon.png'),
  169: require('../assets/images/digimon/169_Musyamon.png'),
  170: require('../assets/images/digimon/170_Mekanorimon.png'),
  171: require('../assets/images/digimon/171_Raremon.png'),
  172: require('../assets/images/digimon/172_Waspmon.png'),
  173: require('../assets/images/digimon/173_Aquilamon.png'),
  174: require('../assets/images/digimon/174_Ankylomon.png'),
  175: require('../assets/images/digimon/175_ExVeemon.png'),
  176: require('../assets/images/digimon/176_Guardromon (Gold).png'),
  177: require('../assets/images/digimon/177_Stingmon.png'),
  178: require('../assets/images/digimon/178_Kurisarimon.png'),
  179: require('../assets/images/digimon/179_Submarimon.png'),
  180: require('../assets/images/digimon/180_Shurimon.png'),
  181: require('../assets/images/digimon/181_Digmon.png'),
  182: require('../assets/images/digimon/182_Nefertimon.png'),
  183: require('../assets/images/digimon/183_Flamedramon.png'),
  184: require('../assets/images/digimon/184_Pegasusmon.png'),
  185: require('../assets/images/digimon/185_Halsemon.png'),
  186: require('../assets/images/digimon/186_Lighdramon.png'),
  187: require('../assets/images/digimon/187_Agunimon.png'),
  188: require('../assets/images/digimon/188_Lobomon.png'),
  189: require('../assets/images/digimon/189_Lanamon.png'),
  190: require('../assets/images/digimon/190_BurningGreymon.png'),
  191: require('../assets/images/digimon/191_Calmaramon.png'),
  192: require('../assets/images/digimon/192_KendoGarurumon.png'),
  193: require('../assets/images/digimon/193_Aegiochusmon.png'),
  194: require('../assets/images/digimon/194_Aegiochusmon: Green.png'),
  195: require('../assets/images/digimon/195_Aegiochusmon: Dark.png'),
  196: require('../assets/images/digimon/196_Aegiochusmon: Blue.png'),
  197: require('../assets/images/digimon/197_Aegiochusmon: Holy.png'),
  198: require('../assets/images/digimon/198_MegaKabuterimon.png'),
  199: require('../assets/images/digimon/199_Andromon.png'),
  200: require('../assets/images/digimon/200_Wingdramon.png'),
  201: require('../assets/images/digimon/201_AeroVeedramon.png'),
  202: require('../assets/images/digimon/202_ExTyrannomon.png'),
  203: require('../assets/images/digimon/203_Angewomon.png'),
  204: require('../assets/images/digimon/204_Garudamon.png'),
  205: require('../assets/images/digimon/205_GrapLeomon.png'),
  206: require('../assets/images/digimon/206_Grademon.png'),
  207: require('../assets/images/digimon/207_GreatGrizzlymon.png'),
  208: require('../assets/images/digimon/208_Cerberusmon.png'),
  209: require('../assets/images/digimon/209_Cerberusmon WM.png'),
  210: require('../assets/images/digimon/210_Cyberdramon.png'),
  211: require('../assets/images/digimon/211_JewelBeemon.png'),
  212: require('../assets/images/digimon/212_Zudomon.png'),
  213: require('../assets/images/digimon/213_Chirinmon.png'),
  214: require('../assets/images/digimon/214_Duramon.png'),
  215: require('../assets/images/digimon/215_Parrotmon.png'),
  216: require('../assets/images/digimon/216_IceLeomon.png'),
  217: require('../assets/images/digimon/217_Hisyaryumon.png'),
  218: require('../assets/images/digimon/218_Butenmon.png'),
  219: require('../assets/images/digimon/219_Flaremon.png'),
  220: require('../assets/images/digimon/220_Whamon.png'),
  221: require('../assets/images/digimon/221_MagnaAngemon.png'),
  222: require('../assets/images/digimon/222_Mammothmon.png'),
  223: require('../assets/images/digimon/223_MetalGreymon.png'),
  224: require('../assets/images/digimon/224_Monzaemon.png'),
  225: require('../assets/images/digimon/225_Crowmon.png'),
  226: require('../assets/images/digimon/226_RizeGreymon.png'),
  227: require('../assets/images/digimon/227_Rapidmon.png'),
  228: require('../assets/images/digimon/228_LoaderLeomon.png'),
  229: require('../assets/images/digimon/229_WereGarurumon.png'),
  230: require('../assets/images/digimon/230_Scorpiomon.png'),
  231: require('../assets/images/digimon/231_Enbarrmon.png'),
  232: require('../assets/images/digimon/232_Antylamon.png'),
  233: require('../assets/images/digimon/233_Meteormon.png'),
  234: require('../assets/images/digimon/234_OmniShoutmon.png'),
  235: require('../assets/images/digimon/235_Kimeramon.png'),
  236: require('../assets/images/digimon/236_CatchMamemon.png'),
  237: require('../assets/images/digimon/237_Crescemon.png'),
  238: require('../assets/images/digimon/238_SuperStarmon.png'),
  239: require('../assets/images/digimon/239_SkullBaluchimon.png'),
  240: require('../assets/images/digimon/240_SaviorHuckmon.png'),
  241: require('../assets/images/digimon/241_Sirenmon.png'),
  242: require('../assets/images/digimon/242_Taomon.png'),
  243: require('../assets/images/digimon/243_Digitamamon.png'),
  244: require('../assets/images/digimon/244_SkullMeramon.png'),
  245: require('../assets/images/digimon/245_Deramon.png'),
  246: require('../assets/images/digimon/246_Triceramon.png'),
  247: require('../assets/images/digimon/247_DoruGreymon.png'),
  248: require('../assets/images/digimon/248_Knightmon.png'),
  249: require('../assets/images/digimon/249_Divermon.png'),
  250: require('../assets/images/digimon/250_Pandamon.png'),
  251: require('../assets/images/digimon/251_Pumpkinmon.png'),
  252: require('../assets/images/digimon/252_BigMamemon.png'),
  253: require('../assets/images/digimon/253_Piximon.png'),
  254: require('../assets/images/digimon/254_HippoGryphonmon.png'),
  255: require('../assets/images/digimon/255_Brachiomon.png'),
  256: require('../assets/images/digimon/256_Volcanomon.png'),
  257: require('../assets/images/digimon/257_MasterBlimpmon.png'),
  258: require('../assets/images/digimon/258_MachGaogamon.png'),
  259: require('../assets/images/digimon/259_Mamemon.png'),
  260: require('../assets/images/digimon/260_MegaSeadramon.png'),
  261: require('../assets/images/digimon/261_MetalMamemon.png'),
  262: require('../assets/images/digimon/262_Lilamon.png'),
  263: require('../assets/images/digimon/263_Lillymon.png'),
  264: require('../assets/images/digimon/264_Locomon.png'),
  265: require('../assets/images/digimon/265_Astamon.png'),
  266: require('../assets/images/digimon/266_Arukenimon.png'),
  267: require('../assets/images/digimon/267_Myotismon.png'),
  268: require('../assets/images/digimon/268_Etemon.png'),
  269: require('../assets/images/digimon/269_Okuwamon.png'),
  270: require('../assets/images/digimon/270_Orochimon.png'),
  271: require('../assets/images/digimon/271_Garbagemon.png'),
  272: require('../assets/images/digimon/272_Gigadramon.png'),
  273: require('../assets/images/digimon/273_CannonBeemon.png'),
  274: require('../assets/images/digimon/274_Groundramon.png'),
  275: require('../assets/images/digimon/275_Sharkmon.png'),
  276: require('../assets/images/digimon/276_Shaujinmon.png'),
  277: require('../assets/images/digimon/277_Cherrymon.png'),
  278: require('../assets/images/digimon/278_SkullGreymon.png'),
  279: require('../assets/images/digimon/279_SkullSatamon.png'),
  280: require('../assets/images/digimon/280_SkullSeadramon.png'),
  281: require('../assets/images/digimon/281_DarkSuperStarmon.png'),
  282: require('../assets/images/digimon/282_Dragomon.png'),
  283: require('../assets/images/digimon/283_Tankdramon.png'),
  284: require('../assets/images/digimon/284_ShogunGekomon.png'),
  285: require('../assets/images/digimon/285_Datamon.png'),
  286: require('../assets/images/digimon/286_Phantomon.png'),
  287: require('../assets/images/digimon/287_BlackKingNumemon.png'),
  288: require('../assets/images/digimon/288_BlueMeramon.png'),
  289: require('../assets/images/digimon/289_Vademon.png'),
  290: require('../assets/images/digimon/290_Matadormon.png'),
  291: require('../assets/images/digimon/291_Mummymon.png'),
  292: require('../assets/images/digimon/292_Mistymon.png'),
  293: require('../assets/images/digimon/293_Megadramon.png'),
  294: require('../assets/images/digimon/294_WarGrowlmon.png'),
  295: require('../assets/images/digimon/295_MetalTyrannomon.png'),
  296: require('../assets/images/digimon/296_Lucemon CM.png'),
  297: require('../assets/images/digimon/297_LadyDevimon.png'),
  298: require('../assets/images/digimon/298_Wisemon.png'),
  299: require('../assets/images/digimon/299_WaruSeadramon.png'),
  300: require('../assets/images/digimon/300_Shakkoumon.png'),
  301: require('../assets/images/digimon/301_Silphymon.png'),
  302: require('../assets/images/digimon/302_Dinobeemon.png'),
  303: require('../assets/images/digimon/303_Paildramon.png'),
  304: require('../assets/images/digimon/304_Infermon.png'),
  305: require('../assets/images/digimon/305_Aldamon.png'),
  306: require('../assets/images/digimon/306_Beowolfmon.png'),
  307: require('../assets/images/digimon/307_Apollomon.png'),
  308: require('../assets/images/digimon/308_Alphamon.png'),
  309: require('../assets/images/digimon/309_UlforceVeedramon.png'),
  310: require('../assets/images/digimon/310_Varodurumon.png'),
  311: require('../assets/images/digimon/311_Venusmon.png'),
  312: require('../assets/images/digimon/312_WarGreymon.png'),
  313: require('../assets/images/digimon/313_Ouryumon.png'),
  314: require('../assets/images/digimon/314_Ophanimon.png'),
  315: require('../assets/images/digimon/315_ClavisAngemon.png'),
  316: require('../assets/images/digimon/316_Craniamon.png'),
  317: require('../assets/images/digimon/317_Eaglemon.png'),
  318: require('../assets/images/digimon/318_Chronomon HM.png'),
  319: require('../assets/images/digimon/319_Cherubimon (Black).png'),
  320: require('../assets/images/digimon/320_Cherubimon (Good).png'),
  321: require('../assets/images/digimon/321_Goldramon.png'),
  322: require('../assets/images/digimon/322_ShineGreymon.png'),
  323: require('../assets/images/digimon/323_Justimon.png'),
  324: require('../assets/images/digimon/324_SkullMammothmon.png'),
  325: require('../assets/images/digimon/325_SlashAngemon.png'),
  326: require('../assets/images/digimon/326_Kentaurosmon.png'),
  327: require('../assets/images/digimon/327_Slayerdramon.png'),
  328: require('../assets/images/digimon/328_Seraphimon.png'),
  329: require('../assets/images/digimon/329_MegaGargomon.png'),
  330: require('../assets/images/digimon/330_Durandamon.png'),
  331: require('../assets/images/digimon/331_Neptunemon.png'),
  332: require('../assets/images/digimon/332_HiAndromon.png'),
  333: require('../assets/images/digimon/333_BanchoLeomon.png'),
  334: require('../assets/images/digimon/334_HerculesKabuterimon.png'),
  335: require('../assets/images/digimon/335_Phoenixmon.png'),
  336: require('../assets/images/digimon/336_Magnadramon.png'),
  337: require('../assets/images/digimon/337_Mastemon.png'),
  338: require('../assets/images/digimon/338_MarineAngemon.png'),
  339: require('../assets/images/digimon/339_Marsmon.png'),
  340: require('../assets/images/digimon/340_Jupitermon.png'),
  341: require('../assets/images/digimon/341_Ravemon.png'),
  342: require('../assets/images/digimon/342_UltimateBrachiomon.png'),
  343: require('../assets/images/digimon/343_Vulcanusmon.png'),
  344: require('../assets/images/digimon/344_Gankoomon.png'),
  345: require('../assets/images/digimon/345_Kuzuhamon.png'),
  346: require('../assets/images/digimon/346_GroundLocomon.png'),
  347: require('../assets/images/digimon/347_Gryphonmon.png'),
  348: require('../assets/images/digimon/348_Ceresmon.png'),
  349: require('../assets/images/digimon/349_Ceresmon Medium.png'),
  350: require('../assets/images/digimon/350_SaberLeomon.png'),
  351: require('../assets/images/digimon/351_Sakuyamon.png'),
  352: require('../assets/images/digimon/352_Jesmon.png'),
  353: require('../assets/images/digimon/353_JumboGamemon.png'),
  354: require('../assets/images/digimon/354_Dianamon.png'),
  355: require('../assets/images/digimon/355_Dynasmon.png'),
  356: require('../assets/images/digimon/356_Leopardmon.png'),
  357: require('../assets/images/digimon/357_Leopardmon LM.png'),
  358: require('../assets/images/digimon/358_Dorugoramon.png'),
  359: require('../assets/images/digimon/359_PileVolcanomon.png'),
  360: require('../assets/images/digimon/360_PrinceMamemon.png'),
  361: require('../assets/images/digimon/361_Plesiomon.png'),
  362: require('../assets/images/digimon/362_Boltmon.png'),
  363: require('../assets/images/digimon/363_MirageGaogamon.png'),
  364: require('../assets/images/digimon/364_MetalGarurumon.png'),
  365: require('../assets/images/digimon/365_MetalSeadramon.png'),
  366: require('../assets/images/digimon/366_MedievalGallantmon.png'),
  367: require('../assets/images/digimon/367_Rosemon.png'),
  368: require('../assets/images/digimon/368_Lotosmon.png'),
  369: require('../assets/images/digimon/369_AvengeKidmon.png'),
  370: require('../assets/images/digimon/370_Ebemon.png'),
  371: require('../assets/images/digimon/371_VenomMyotismon.png'),
  372: require('../assets/images/digimon/372_AncientWisemon.png'),
  373: require('../assets/images/digimon/373_Gaiomon.png'),
  374: require('../assets/images/digimon/374_ChaosGallantmon.png'),
  375: require('../assets/images/digimon/375_Chaosdramon.png'),
  376: require('../assets/images/digimon/376_Callismon.png'),
  377: require('../assets/images/digimon/377_Gundramon.png'),
  378: require('../assets/images/digimon/378_KingEtemon.png'),
  379: require('../assets/images/digimon/379_GranDracmon.png'),
  380: require('../assets/images/digimon/380_Chronomon DM.png'),
  381: require('../assets/images/digimon/381_Zanbamon.png'),
  382: require('../assets/images/digimon/382_ZombiePlutomon.png'),
  383: require('../assets/images/digimon/383_Darkdramon.png'),
  384: require('../assets/images/digimon/384_TigerVespamon.png'),
  385: require('../assets/images/digimon/385_Titamon.png'),
  386: require('../assets/images/digimon/386_TyrantKabuterimon.png'),
  387: require('../assets/images/digimon/387_Creepymon.png'),
  388: require('../assets/images/digimon/388_Gallantmon.png'),
  389: require('../assets/images/digimon/389_Bacchusmon.png'),
  390: require('../assets/images/digimon/390_Bacchusmon DM.png'),
  391: require('../assets/images/digimon/391_Barbamon.png'),
  392: require('../assets/images/digimon/392_Piedmon.png'),
  393: require('../assets/images/digimon/393_Puppetmon.png'),
  394: require('../assets/images/digimon/394_Pharaohmon.png'),
  395: require('../assets/images/digimon/395_Pukumon.png'),
  396: require('../assets/images/digimon/396_PlatinumNumemon.png'),
  397: require('../assets/images/digimon/397_Plutomon.png'),
  398: require('../assets/images/digimon/398_Breakdramon.png'),
  399: require('../assets/images/digimon/399_MaloMyotismon.png'),
  400: require('../assets/images/digimon/400_BeelStarmon.png'),
  401: require('../assets/images/digimon/401_Beelzemon.png'),
  402: require('../assets/images/digimon/402_Belphemon SM.png'),
  403: require('../assets/images/digimon/403_MagnaKidmon.png'),
  404: require('../assets/images/digimon/404_Minervamon.png'),
  405: require('../assets/images/digimon/405_Millenniummon.png'),
  406: require('../assets/images/digimon/406_Machinedramon.png'),
  407: require('../assets/images/digimon/407_Megidramon.png'),
  408: require('../assets/images/digimon/408_MetalEtemon.png'),
  409: require('../assets/images/digimon/409_Merukimon.png'),
  410: require('../assets/images/digimon/410_Junomon.png'),
  411: require('../assets/images/digimon/411_Junomon HM.png'),
  412: require('../assets/images/digimon/412_RustTyrannomon.png'),
  413: require('../assets/images/digimon/413_Leviamon.png'),
  414: require('../assets/images/digimon/414_Lilithmon.png'),
  415: require('../assets/images/digimon/415_LordKnightmon.png'),
  416: require('../assets/images/digimon/416_Imperialdramon DM.png'),
  417: require('../assets/images/digimon/417_Imperialdramon FM.png'),
  418: require('../assets/images/digimon/418_Vikemon.png'),
  419: require('../assets/images/digimon/419_Valkyrimon.png'),
  420: require('../assets/images/digimon/420_GranKuwagamon.png'),
  421: require('../assets/images/digimon/421_Diaboromon.png'),
  422: require('../assets/images/digimon/422_Rapidmon (Armor).png'),
  423: require('../assets/images/digimon/423_Magnamon.png'),
  424: require('../assets/images/digimon/424_EmperorGreymon.png'),
  425: require('../assets/images/digimon/425_MagnaGarurumon.png'),
  426: require('../assets/images/digimon/426_MagnaGarurumon (Detached).png'),
  427: require('../assets/images/digimon/427_Alphamon: Ouryuken.png'),
  428: require('../assets/images/digimon/428_Craniamon + Enbarrmon.png'),
  429: require('../assets/images/digimon/429_Imperialdramon PM.png'),
  430: require('../assets/images/digimon/430_Omnimon.png'),
  431: require('../assets/images/digimon/431_Omnimon Zwart.png'),
  432: require('../assets/images/digimon/432_Chaosmon.png'),
  433: require('../assets/images/digimon/433_Chaosmon: Valdur Arm.png'),
  434: require('../assets/images/digimon/434_GraceNovamon.png'),
  435: require('../assets/images/digimon/435_ShineGreymon BM.png'),
  436: require('../assets/images/digimon/436_Susanomon.png'),
  437: require('../assets/images/digimon/437_Jupitermon WM.png'),
  438: require('../assets/images/digimon/438_Ravemon BM.png'),
  439: require('../assets/images/digimon/439_Examon.png'),
  440: require('../assets/images/digimon/440_MirageGaogamon BM.png'),
  441: require('../assets/images/digimon/441_Rosemon BM.png'),
  442: require('../assets/images/digimon/442_Titamon + SkullBaluchimon.png'),
  443: require('../assets/images/digimon/443_Gallantmon CM.png'),
  444: require('../assets/images/digimon/444_Beelzemon BM.png'),
  445: require('../assets/images/digimon/445_Belphemon RM.png'),
  446: require('../assets/images/digimon/446_Mervamon.png'),
  447: require('../assets/images/digimon/447_Lucemon SM.png'),
  448: require('../assets/images/digimon/448_Armageddemon.png'),
  449: require('../assets/images/digimon/449_Agumon (Bond of Bravery).png'),
  450: require('../assets/images/digimon/450_Apocalymon.png'),
  451: require('../assets/images/digimon/451_Gabumon (Bond of Friendship).png'),
  468: require('../assets/images/digimon/468_Agumon (Black).png'),
  469: require('../assets/images/digimon/469_Gabumon (Black).png'),
  470: require('../assets/images/digimon/470_Garurumon (Black).png'),
  471: require('../assets/images/digimon/471_Greymon (Blue).png'),
  472: require('../assets/images/digimon/472_MetalGreymon (Blue).png'),
  473: require('../assets/images/digimon/473_WereGarurumon (Black).png'),
  474: require('../assets/images/digimon/474_BlackWarGreymon.png'),
  475: require('../assets/images/digimon/475_MetalGarurumon (Black).png'),
} as const;
